---
format: html
toc: true
toc-depth: 2
embed-resources: true
execute: 
  eval: true
  echo: false
  warning: false
  error: false
---

```{r}
#| label: load helper functions

source(here::here("R", "02_manipulate_value_labels.R"))

```

```{r}
#| label: load
qnr_ehcvm2 <- fs::path(here::here(), "01_entree", "ehcvm2", "document.json") |>
  susometa::parse_questionnaire()

unit_vars <- c(
  "s07Bq03b_cereales",
  "s07Bq03b_viandes",
  "s07Bq03b_poissons",
  "s07Bq03b_huiles",
  "s07Bq03b_laitier",
  "s07Bq03b_fruits",
  "s07Bq03b_legumes",
  "s07Bq03b_legtub",
  "s07Bq03b_sucreries",
  "s07Bq03b_epices",
  "s07Bq03b_boissons"
)

unites_tbls <- purrr::map(
  .x = unit_vars,
  .f = ~ create_units_tbl(
    qnr_df = qnr_ehcvm2,
    varname = .x
  )
)
```

## Toutes les unité ensemble

```{r}
#| label: all food groups
unites_all_groups_tbl <- dplyr::bind_rows(unites_tbls) |>
	dplyr::distinct(unite_code, unite_texte, .keep_all = TRUE)

unites_all <- unites_all_groups_tbl |>
	gt::gt() |>
  gt::opt_interactive(
    use_pagination = TRUE,
    page_size_default = 15,
    use_highlight = TRUE,
    use_filters = TRUE,
    use_resizers = TRUE
  )

unites_all
```

## Unités par groupe de produits

### Céréales

```{r}
#| label: cereales
gt::gt(unites_tbls[[1]])
```

### Viandes

```{r}
#| label: viandes
gt::gt(unites_tbls[[2]])
```

### Poissons et fruits de mer

```{r}
#| label: poissons
gt::gt(unites_tbls[[3]])
```

### Lait, fromage, et oeufs

```{r}
#| label: laitier
gt::gt(unites_tbls[[4]])
```

### Huiles et graisses

```{r}
#| label: huiles
gt::gt(unites_tbls[[5]])
```

### Fruits

```{r}
#| label: fruits
gt::gt(unites_tbls[[6]])
```

### Légumes

```{r}
#| label: legumes
gt::gt(unites_tbls[[7]])
```

### Légumineuses et tubercules

```{r}
#| label: leg_tub
gt::gt(unites_tbls[[8]])
```

### Sucre, miel, chocolat, et confiserie

```{r}
#| label: sucreries
gt::gt(unites_tbls[[9]])
```

### Épices, condiments, et autres

```{r}
#| label: epices
gt::gt(unites_tbls[[10]])
```

### Boissons

```{r}
#| label: boissons
gt::gt(unites_tbls[[11]])
```
